---
title: Wayfare
timezone: UTC
collections:
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/stories/:year/:month/:day/:title/"
    excerpt_separator: "<!-- more -->"
    nav:
      id: post
      site:
        highlight: stories
      side:
        id: stories
        categories: true
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: events
  values:
    headline: 
    images:
      splash_image: 
      thumb_image: 
    dates:
      start_date: 
      end_date: 
    urls:
      ticket_url: 
    location: 
permalink: pretty
gems:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
