---
title: Wayfare
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/stories/:year/:month/:day/:title/"
    author: 
    nav:
      id: post
      site:
        highlight: stories
      side:
        id: stories
        categories: true
    excerpt_separator: "<!-- more -->"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: 
- scope:
    path: ''
    type: events
  values:
    headline: 
    images:
      splash_image: 
      thumb_image: 
    dates:
      start_date: 
      end_date: 
    urls:
      ticket_url: 
    location: 
- scope:
    path: ''
    type: authors
  values:
    layout: page
    company_name: 
    job_title: 
    bio_image: 
    is_guest: 
twitter:
  username: wayfarehq
facebook:
  publisher: https://www.facebook.com/WayfareHQ/
logo: "/assets/images/wayfare-logo@2x.png"
social:
  name: Wayfare
  links:
  - https://www.facebook.com/WayfareHQ/
  - https://www.instagram.com/wayfarehq/
  - https://twitter.com/wayfarehq
  - https://www.linkedin.com/company/wayfare-hq
permalink: pretty
paginate: 10
paginate_path: "/stories/archive/page:num"
gems:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
whitelist:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
